//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ChargeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChargeResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ChargeResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;p align=&apos;center&apos;&gt;&lt;br/&gt;&lt;br/&gt;对不起，阅读{$ItemName}需要消耗 &lt;b&gt;&lt;font color=red&gt;{$NeedPoint}&lt;/font&gt;&lt;/b&gt; {$PointUnit}{$PointName}！而你目前只有 &lt;b&gt;&lt;font color=blue&gt;{$NowPoint}&lt;/font&gt;&lt;/b&gt; {$PointUnit}{$PointName}可用。{$PointName}数不足，无法阅读本文。请与我们联系进行充值。&lt;/p&gt; 的本地化字符串。
        /// </summary>
        internal static string NeedPoint {
            get {
                return ResourceManager.GetString("NeedPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;li&gt;对不起，您尚未通过管理员审核，不能查看收费项目。&lt;/li&gt; 的本地化字符串。
        /// </summary>
        internal static string NoCheck {
            get {
                return ResourceManager.GetString("NoCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;br/&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;你还没注册？或者没有登录？这篇{$ItemName}要求至少是本站的注册会员才能阅读！&lt;br/&gt;&lt;br/&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;如果你还没注册，请赶紧&lt;a href=&apos;{$InstallDir}User/Register.aspx&apos;&gt;&lt;font color=red&gt;点此注册&lt;/font&gt;&lt;/a&gt;吧！&lt;br/&gt;&lt;br/&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;如果你已经注册但还没登录，请赶紧&lt;a href=&apos;{$InstallDir}User/Login.aspx?ReturnUrl={$ReturnUrl}&apos;&gt;&lt;font color=red&gt;点此登录&lt;/font&gt;&lt;/a&gt;吧！&lt;br/&gt;&lt;br/&gt; 的本地化字符串。
        /// </summary>
        internal static string NoLogin {
            get {
                return ResourceManager.GetString("NoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;li&gt;对不起，您尚未通过邮件验证，不能查看此项目。&lt;/li&gt; 的本地化字符串。
        /// </summary>
        internal static string NoMail {
            get {
                return ResourceManager.GetString("NoMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;p align=&apos;center&apos;&gt;&lt;br/&gt;&lt;br/&gt;&lt;font color=red&gt;对不起，{$ItemName}为收费内容，而您的有效期已经过期，所以无法阅读本文。请与我们联系进行充值。&lt;/font&gt;&lt;/p&gt; 的本地化字符串。
        /// </summary>
        internal static string OutTime {
            get {
                return ResourceManager.GetString("OutTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;li&gt;你已经达到或超过今天所能查看的信息总数！&lt;/li&gt; 的本地化字符串。
        /// </summary>
        internal static string Overflow_Today {
            get {
                return ResourceManager.GetString("Overflow_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;li&gt;你已经达到或超过有效期内所能查看的信息总数！&lt;/li&gt; 的本地化字符串。
        /// </summary>
        internal static string Overflow_Total {
            get {
                return ResourceManager.GetString("Overflow_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;li&gt;对不起，您没有查看此栏目内容的权限！&lt;/li&gt; 的本地化字符串。
        /// </summary>
        internal static string PurviewCheckedErr {
            get {
                return ResourceManager.GetString("PurviewCheckedErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;li&gt;对不起，您没有查看此信息的权限！&lt;/li&gt; 的本地化字符串。
        /// </summary>
        internal static string PurviewCheckedErr2 {
            get {
                return ResourceManager.GetString("PurviewCheckedErr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;p align=&apos;center&apos;&gt;&lt;br/&gt;&lt;br/&gt;阅读{$ItemName}需要消耗 &lt;b&gt;&lt;font color=red&gt;{$InfoPoint}&lt;/font&gt;&lt;/b&gt; {$PointUnit}{$PointName}！你目前尚有 &lt;b&gt;&lt;font color=blue&gt;{$NowPoint}&lt;/font&gt;&lt;/b&gt; {$PointUnit}{$PointName}可用。阅读本文后，你将剩下 &lt;b&gt;&lt;font color=green&gt;{$FinalPoint}&lt;/font&gt;&lt;/b&gt; {$PointUnit}{$PointName}&lt;br/&gt;&lt;br/&gt;你确实愿意花费 &lt;b&gt;&lt;font color=red&gt;{$InfoPoint}&lt;/font&gt;&lt;/b&gt; {$PointUnit}{$PointName}来阅读本文吗？&lt;br/&gt;&lt;br/&gt;&lt;a href=&apos;{$url}&apos;&gt;我愿意&lt;/a&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;a href=&apos;{$InstallDir}index.aspx&apos;&gt;我不愿意&lt;/a&gt;&lt;/p&gt; 的本地化字符串。
        /// </summary>
        internal static string UsePoint {
            get {
                return ResourceManager.GetString("UsePoint", resourceCulture);
            }
        }
    }
}
