//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnumResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.EnumResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 矩形横幅 的本地化字符串。
        /// </summary>
        internal static string ADZoneType_Banner {
            get {
                return ResourceManager.GetString("ADZoneType_Banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文字代码 的本地化字符串。
        /// </summary>
        internal static string ADZoneType_Code {
            get {
                return ResourceManager.GetString("ADZoneType_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对联广告 的本地化字符串。
        /// </summary>
        internal static string ADZoneType_Couplet {
            get {
                return ResourceManager.GetString("ADZoneType_Couplet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 固定位置 的本地化字符串。
        /// </summary>
        internal static string ADZoneType_Fixed {
            get {
                return ResourceManager.GetString("ADZoneType_Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 漂浮移动 的本地化字符串。
        /// </summary>
        internal static string ADZoneType_Float {
            get {
                return ResourceManager.GetString("ADZoneType_Float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 随屏移动 的本地化字符串。
        /// </summary>
        internal static string ADZoneType_Move {
            get {
                return ResourceManager.GetString("ADZoneType_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 弹出窗口 的本地化字符串。
        /// </summary>
        internal static string ADZoneType_Pop {
            get {
                return ResourceManager.GetString("ADZoneType_Pop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 企业主要联系人 的本地化字符串。
        /// </summary>
        internal static string ContacterType_EnterpriceMainContacter {
            get {
                return ResourceManager.GetString("ContacterType_EnterpriceMainContacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 企业次要联系人 的本地化字符串。
        /// </summary>
        internal static string ContacterType_EnterpriceSecondContacter {
            get {
                return ResourceManager.GetString("ContacterType_EnterpriceSecondContacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个人会员 的本地化字符串。
        /// </summary>
        internal static string ContacterType_Persional {
            get {
                return ResourceManager.GetString("ContacterType_Persional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;font color=&quot;blue&quot;&gt;已发货&lt;/font&gt; 的本地化字符串。
        /// </summary>
        internal static string DeliverStatus_Consignment {
            get {
                return ResourceManager.GetString("DeliverStatus_Consignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;font color=&quot;red&quot;&gt;配送中&lt;/font&gt; 的本地化字符串。
        /// </summary>
        internal static string DeliverStatus_Preparative {
            get {
                return ResourceManager.GetString("DeliverStatus_Preparative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;font color=&quot;green&quot;&gt;已签收&lt;/font&gt; 的本地化字符串。
        /// </summary>
        internal static string DeliverStatus_SignIn {
            get {
                return ResourceManager.GetString("DeliverStatus_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代理商组 的本地化字符串。
        /// </summary>
        internal static string GroupType_Agent {
            get {
                return ResourceManager.GetString("GroupType_Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 会员组 的本地化字符串。
        /// </summary>
        internal static string GroupType_Register {
            get {
                return ResourceManager.GetString("GroupType_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 越权 的本地化字符串。
        /// </summary>
        internal static string LogCategory_ExceedAuthority {
            get {
                return ResourceManager.GetString("LogCategory_ExceedAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异常 的本地化字符串。
        /// </summary>
        internal static string LogCategory_Exception {
            get {
                return ResourceManager.GetString("LogCategory_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录失败 的本地化字符串。
        /// </summary>
        internal static string LogCategory_LoginFailure {
            get {
                return ResourceManager.GetString("LogCategory_LoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录成功 的本地化字符串。
        /// </summary>
        internal static string LogCategory_LoginOk {
            get {
                return ResourceManager.GetString("LogCategory_LoginOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        internal static string LogCategory_LogOut {
            get {
                return ResourceManager.GetString("LogCategory_LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没分类 的本地化字符串。
        /// </summary>
        internal static string LogCategory_None {
            get {
                return ResourceManager.GetString("LogCategory_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高 的本地化字符串。
        /// </summary>
        internal static string LogPriority_High {
            get {
                return ResourceManager.GetString("LogPriority_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最高 的本地化字符串。
        /// </summary>
        internal static string LogPriority_Highest {
            get {
                return ResourceManager.GetString("LogPriority_Highest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 低 的本地化字符串。
        /// </summary>
        internal static string LogPriority_Low {
            get {
                return ResourceManager.GetString("LogPriority_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最低 的本地化字符串。
        /// </summary>
        internal static string LogPriority_Lowest {
            get {
                return ResourceManager.GetString("LogPriority_Lowest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常规 的本地化字符串。
        /// </summary>
        internal static string LogPriority_Normal {
            get {
                return ResourceManager.GetString("LogPriority_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发货通知 的本地化字符串。
        /// </summary>
        internal static string MessageTitle_Deliver {
            get {
                return ResourceManager.GetString("MessageTitle_Deliver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单确认通知 的本地化字符串。
        /// </summary>
        internal static string MessageTitle_OrderConfirm {
            get {
                return ResourceManager.GetString("MessageTitle_OrderConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开具发票通知 的本地化字符串。
        /// </summary>
        internal static string MessageTitle_OrderInvoiceAdd {
            get {
                return ResourceManager.GetString("MessageTitle_OrderInvoiceAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退款通知 的本地化字符串。
        /// </summary>
        internal static string MessageTitle_OrderRefund {
            get {
                return ResourceManager.GetString("MessageTitle_OrderRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 充值卡交付通知 的本地化字符串。
        /// </summary>
        internal static string MessageTitle_OrderSendCard {
            get {
                return ResourceManager.GetString("MessageTitle_OrderSendCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 银行支付通知 的本地化字符串。
        /// </summary>
        internal static string MessageTitle_ReceiptMoney {
            get {
                return ResourceManager.GetString("MessageTitle_ReceiptMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;font color=&quot;blue&quot;&gt;已经确认&lt;/font&gt; 的本地化字符串。
        /// </summary>
        internal static string OrderStatus_Confirmed {
            get {
                return ResourceManager.GetString("OrderStatus_Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;font color=&quot;gray&quot;&gt;已结清&lt;/font&gt; 的本地化字符串。
        /// </summary>
        internal static string OrderStatus_End {
            get {
                return ResourceManager.GetString("OrderStatus_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂停处理 的本地化字符串。
        /// </summary>
        internal static string OrderStatus_Pause {
            get {
                return ResourceManager.GetString("OrderStatus_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经作废 的本地化字符串。
        /// </summary>
        internal static string OrderStatus_Rubbish {
            get {
                return ResourceManager.GetString("OrderStatus_Rubbish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;font color=&quot;red&quot;&gt;等待确认&lt;/font&gt; 的本地化字符串。
        /// </summary>
        internal static string OrderStatus_WaitForConfirm {
            get {
                return ResourceManager.GetString("OrderStatus_WaitForConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缺货时，取消此订单 的本地化字符串。
        /// </summary>
        internal static string OutOfStockProject_CancelOrder {
            get {
                return ResourceManager.GetString("OutOfStockProject_CancelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缺货时，将有货的商品发出，取消无货商品的订购 的本地化字符串。
        /// </summary>
        internal static string OutOfStockProject_SendPartGoods {
            get {
                return ResourceManager.GetString("OutOfStockProject_SendPartGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;font color=&quot;Blue&quot;&gt;已经付清&lt;/font&gt; 的本地化字符串。
        /// </summary>
        internal static string PayStatus_Payoff {
            get {
                return ResourceManager.GetString("PayStatus_Payoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;font color=&quot;Green&quot;&gt;已收定金&lt;/font&gt; 的本地化字符串。
        /// </summary>
        internal static string PayStatus_ReceivedEarnest {
            get {
                return ResourceManager.GetString("PayStatus_ReceivedEarnest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;font color=&quot;red&quot;&gt;等待汇款&lt;/font&gt; 的本地化字符串。
        /// </summary>
        internal static string PayStatus_WaitForPay {
            get {
                return ResourceManager.GetString("PayStatus_WaitForPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点卡 的本地化字符串。
        /// </summary>
        internal static string ProductCharacter_Card {
            get {
                return ResourceManager.GetString("ProductCharacter_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载 的本地化字符串。
        /// </summary>
        internal static string ProductCharacter_Download {
            get {
                return ResourceManager.GetString("ProductCharacter_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实物 的本地化字符串。
        /// </summary>
        internal static string ProductCharacter_Practicality {
            get {
                return ResourceManager.GetString("ProductCharacter_Practicality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务 的本地化字符串。
        /// </summary>
        internal static string ProductCharacter_Service {
            get {
                return ResourceManager.GetString("ProductCharacter_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组合型商品 的本地化字符串。
        /// </summary>
        internal static string ProductKind_Component {
            get {
                return ResourceManager.GetString("ProductKind_Component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多属性商品 的本地化字符串。
        /// </summary>
        internal static string ProductKind_Multiattribute {
            get {
                return ResourceManager.GetString("ProductKind_Multiattribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单一型商品 的本地化字符串。
        /// </summary>
        internal static string ProductKind_Single {
            get {
                return ResourceManager.GetString("ProductKind_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 降价商品 的本地化字符串。
        /// </summary>
        internal static string ProductType_Drop {
            get {
                return ResourceManager.GetString("ProductType_Drop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正常销售商品 的本地化字符串。
        /// </summary>
        internal static string ProductType_Normal {
            get {
                return ResourceManager.GetString("ProductType_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 促销礼品 的本地化字符串。
        /// </summary>
        internal static string ProductType_Promotion {
            get {
                return ResourceManager.GetString("ProductType_Promotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 涨价商品 的本地化字符串。
        /// </summary>
        internal static string ProductType_Rise {
            get {
                return ResourceManager.GetString("ProductType_Rise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 特价商品 的本地化字符串。
        /// </summary>
        internal static string ProductType_Special {
            get {
                return ResourceManager.GetString("ProductType_Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日 的本地化字符串。
        /// </summary>
        internal static string ServiceTermUnit_Day {
            get {
                return ResourceManager.GetString("ServiceTermUnit_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 月 的本地化字符串。
        /// </summary>
        internal static string ServiceTermUnit_Month {
            get {
                return ResourceManager.GetString("ServiceTermUnit_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年 的本地化字符串。
        /// </summary>
        internal static string ServiceTermUnit_Year {
            get {
                return ResourceManager.GetString("ServiceTermUnit_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 签收中 的本地化字符串。
        /// </summary>
        internal static string SigninStatus_NotSignin {
            get {
                return ResourceManager.GetString("SigninStatus_NotSignin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已签收 的本地化字符串。
        /// </summary>
        internal static string SigninStatus_Signined {
            get {
                return ResourceManager.GetString("SigninStatus_Signined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未启用签收文档 的本地化字符串。
        /// </summary>
        internal static string SigninType_DisableSignin {
            get {
                return ResourceManager.GetString("SigninType_DisableSignin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 专属文档 的本地化字符串。
        /// </summary>
        internal static string SigninType_EnableSigninPrivate {
            get {
                return ResourceManager.GetString("SigninType_EnableSigninPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公众文档 的本地化字符串。
        /// </summary>
        internal static string SigninType_EnableSigninPublic {
            get {
                return ResourceManager.GetString("SigninType_EnableSigninPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不含税，开发票时需要加收税费 的本地化字符串。
        /// </summary>
        internal static string TaxRateType_BarringTaxNeedInvoiceAddTax {
            get {
                return ResourceManager.GetString("TaxRateType_BarringTaxNeedInvoiceAddTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不含税，开发票时不需要加收税费 的本地化字符串。
        /// </summary>
        internal static string TaxRateType_BarringTaxNeedInvoiceNoTax {
            get {
                return ResourceManager.GetString("TaxRateType_BarringTaxNeedInvoiceNoTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 含税，不开发票时有税率优惠 的本地化字符串。
        /// </summary>
        internal static string TaxRateType_IncludeTaxNoInvoiceFavourable {
            get {
                return ResourceManager.GetString("TaxRateType_IncludeTaxNoInvoiceFavourable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 含税，不开发票时没有税率优惠 的本地化字符串。
        /// </summary>
        internal static string TaxRateType_IncludeTaxNoInvoiceNoFavourable {
            get {
                return ResourceManager.GetString("TaxRateType_IncludeTaxNoInvoiceNoFavourable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正常 的本地化字符串。
        /// </summary>
        internal static string UserLoginState_Approve {
            get {
                return ResourceManager.GetString("UserLoginState_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未通过邮件验证 的本地化字符串。
        /// </summary>
        internal static string UserLoginState_BadValidateByEmail {
            get {
                return ResourceManager.GetString("UserLoginState_BadValidateByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁定 的本地化字符串。
        /// </summary>
        internal static string UserLoginState_Locked {
            get {
                return ResourceManager.GetString("UserLoginState_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未通过管理员认证 的本地化字符串。
        /// </summary>
        internal static string UserLoginState_Unapprove {
            get {
                return ResourceManager.GetString("UserLoginState_Unapprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未通过手机验证 的本地化字符串。
        /// </summary>
        internal static string UserLoginState_UnvalidateByMobile {
            get {
                return ResourceManager.GetString("UserLoginState_UnvalidateByMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已婚 的本地化字符串。
        /// </summary>
        internal static string UserMarriageType_Married {
            get {
                return ResourceManager.GetString("UserMarriageType_Married", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保密 的本地化字符串。
        /// </summary>
        internal static string UserMarriageType_Secrecy {
            get {
                return ResourceManager.GetString("UserMarriageType_Secrecy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 离异 的本地化字符串。
        /// </summary>
        internal static string UserMarriageType_Separate {
            get {
                return ResourceManager.GetString("UserMarriageType_Separate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未婚 的本地化字符串。
        /// </summary>
        internal static string UserMarriageType_Single {
            get {
                return ResourceManager.GetString("UserMarriageType_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 女性 的本地化字符串。
        /// </summary>
        internal static string UserSexType_Female {
            get {
                return ResourceManager.GetString("UserSexType_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 男性 的本地化字符串。
        /// </summary>
        internal static string UserSexType_Male {
            get {
                return ResourceManager.GetString("UserSexType_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保密 的本地化字符串。
        /// </summary>
        internal static string UserSexType_Secrecy {
            get {
                return ResourceManager.GetString("UserSexType_Secrecy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;span style=&quot;color:Red&quot;&gt;锁定&lt;/span&gt; 的本地化字符串。
        /// </summary>
        internal static string UserStatus_Locked {
            get {
                return ResourceManager.GetString("UserStatus_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;span style=&quot;color:Green&quot;&gt;正常&lt;/span&gt; 的本地化字符串。
        /// </summary>
        internal static string UserStatus_None {
            get {
                return ResourceManager.GetString("UserStatus_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未通过管理员认证 的本地化字符串。
        /// </summary>
        internal static string UserStatus_WaitValidateByAdmin {
            get {
                return ResourceManager.GetString("UserStatus_WaitValidateByAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未通过邮件验证 的本地化字符串。
        /// </summary>
        internal static string UserStatus_WaitValidateByEmail {
            get {
                return ResourceManager.GetString("UserStatus_WaitValidateByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未通过手机验证 的本地化字符串。
        /// </summary>
        internal static string UserStatus_WaitValidateByMobile {
            get {
                return ResourceManager.GetString("UserStatus_WaitValidateByMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 企业会员（管理员） 的本地化字符串。
        /// </summary>
        internal static string UserType_administrators {
            get {
                return ResourceManager.GetString("UserType_administrators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 企业会员（待审核成员） 的本地化字符串。
        /// </summary>
        internal static string UserType_AuditingLeaguer {
            get {
                return ResourceManager.GetString("UserType_AuditingLeaguer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 企业会员（普通成员） 的本地化字符串。
        /// </summary>
        internal static string UserType_CommonLeaguer {
            get {
                return ResourceManager.GetString("UserType_CommonLeaguer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 企业会员（创建者） 的本地化字符串。
        /// </summary>
        internal static string UserType_Creator {
            get {
                return ResourceManager.GetString("UserType_Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个人会员 的本地化字符串。
        /// </summary>
        internal static string UserType_Persional {
            get {
                return ResourceManager.GetString("UserType_Persional", resourceCulture);
            }
        }
    }
}
