//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ErrorMessage", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 保存数据失败！ 的本地化字符串。
        /// </summary>
        internal static string Bank_SaveFailure {
            get {
                return ResourceManager.GetString("Bank_SaveFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已存在相同的账户名！ 的本地化字符串。
        /// </summary>
        internal static string Bank_ShortNameExists {
            get {
                return ResourceManager.GetString("Bank_ShortNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对不起！您的IP被系统限定。您可以和站长联系。 的本地化字符串。
        /// </summary>
        internal static string IPRefusedVisit {
            get {
                return ResourceManager.GetString("IPRefusedVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对不起！您的IP被系统限定，不能访问管理后台，您可以和站长联系。 的本地化字符串。
        /// </summary>
        internal static string IPRefusedVisitAdmin {
            get {
                return ResourceManager.GetString("IPRefusedVisitAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此管理员不允许多人同时登录，请重新登录。 的本地化字符串。
        /// </summary>
        internal static string MultiAdminLoginSystem {
            get {
                return ResourceManager.GetString("MultiAdminLoginSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此账号不允许多人同时登录，请重新登录。 的本地化字符串。
        /// </summary>
        internal static string MultiUserLoginSystem {
            get {
                return ResourceManager.GetString("MultiUserLoginSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;li&gt;缺少参数！&lt;/li&gt; 的本地化字符串。
        /// </summary>
        internal static string PageParamLessThen {
            get {
                return ResourceManager.GetString("PageParamLessThen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;li&gt;参数太多！&lt;/li&gt; 的本地化字符串。
        /// </summary>
        internal static string PageParamMoreThen {
            get {
                return ResourceManager.GetString("PageParamMoreThen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;li&gt;参数错误！&lt;/li&gt; 的本地化字符串。
        /// </summary>
        internal static string PageParamNotContains {
            get {
                return ResourceManager.GetString("PageParamNotContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;li&gt;参数值不符！&lt;/li&gt; 的本地化字符串。
        /// </summary>
        internal static string PageParamUnequal {
            get {
                return ResourceManager.GetString("PageParamUnequal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 访问地址错误！ 的本地化字符串。
        /// </summary>
        internal static string PathIsNotExists {
            get {
                return ResourceManager.GetString("PathIsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对不起，为了系统安全，不允许直接输入地址访问本系统的后台管理页面。 的本地化字符串。
        /// </summary>
        internal static string UrlReferrerIsNull {
            get {
                return ResourceManager.GetString("UrlReferrerIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对不起，为了系统安全，不允许从外部链接地址访问本系统的后台管理页面。 的本地化字符串。
        /// </summary>
        internal static string UrlReferrerIsOuter {
            get {
                return ResourceManager.GetString("UrlReferrerIsOuter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您登录的帐户不正常，请与网站管理员联系。 的本地化字符串。
        /// </summary>
        internal static string UserIsNotApprove {
            get {
                return ResourceManager.GetString("UserIsNotApprove", resourceCulture);
            }
        }
    }
}
