//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SiteMapPathResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SiteMapPathResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SiteMapPathResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 地区中含有 &lt;span style=&apos;Color:#F00&apos;&gt;{$Key}&lt;/span&gt; 的信息 的本地化字符串。
        /// </summary>
        internal static string AddressArea {
            get {
                return ResourceManager.GetString("AddressArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收货人名中含有 &lt;span style=&apos;Color:#F00&apos;&gt;{$Key}&lt;/span&gt; 的地址信息 的本地化字符串。
        /// </summary>
        internal static string AddressConsigneeName {
            get {
                return ResourceManager.GetString("AddressConsigneeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电话号码中含有 &lt;span style=&apos;Color:#F00&apos;&gt;{$Key}&lt;/span&gt; 的地址信息 的本地化字符串。
        /// </summary>
        internal static string AddressHomePhone {
            get {
                return ResourceManager.GetString("AddressHomePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机号码中含有 &lt;span style=&apos;Color:#F00&apos;&gt;{$Key}&lt;/span&gt; 的地址信息 的本地化字符串。
        /// </summary>
        internal static string AddressMobile {
            get {
                return ResourceManager.GetString("AddressMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 街道地址中含有 &lt;span style=&apos;Color:#F00&apos;&gt;{$Key}&lt;/span&gt; 的地址信息 的本地化字符串。
        /// </summary>
        internal static string AddressStreet {
            get {
                return ResourceManager.GetString("AddressStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名中含有 &lt;span style=&apos;Color:#F00&apos;&gt;{$Key}&lt;/span&gt; 的地址信息 的本地化字符串。
        /// </summary>
        internal static string AddressUserName {
            get {
                return ResourceManager.GetString("AddressUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮政编码中含有 &lt;span style=&apos;Color:#F00&apos;&gt;{$Key}&lt;/span&gt; 的地址信息 的本地化字符串。
        /// </summary>
        internal static string AddressZipCode {
            get {
                return ResourceManager.GetString("AddressZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索广告简介含有 &lt;span style=&apos;color:#ff0000&apos;&gt;{$Keyword}&lt;/span&gt; 的关键字 的本地化字符串。
        /// </summary>
        internal static string ADIntro {
            get {
                return ResourceManager.GetString("ADIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索广告名称含有 &lt;span style=&apos;color:#ff0000&apos;&gt;{$Keyword}&lt;/span&gt; 的关键字 的本地化字符串。
        /// </summary>
        internal static string ADName {
            get {
                return ResourceManager.GetString("ADName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索版位简介含有 &lt;span style=&apos;color:#ff0000&apos;&gt;{$Keyword}&lt;/span&gt; 的关键字 的本地化字符串。
        /// </summary>
        internal static string ADZoneIntro {
            get {
                return ResourceManager.GetString("ADZoneIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索版位名称含有 &lt;span style=&apos;color:#ff0000&apos;&gt;{$Keyword}&lt;/span&gt; 的关键字 的本地化字符串。
        /// </summary>
        internal static string ADZoneName {
            get {
                return ResourceManager.GetString("ADZoneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在{@CardStatus}{@CardType}中搜索{@Field}: &lt;span style=&apos;Color:#F00&apos;&gt;{$Keyword}&lt;/span&gt; 的本地化字符串。
        /// </summary>
        internal static string CardsSearch {
            get {
                return ResourceManager.GetString("CardsSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户ID等于 &lt;span style=&apos;Color:#F00&apos;&gt;{$Keyword}&lt;/span&gt; 的数据 的本地化字符串。
        /// </summary>
        internal static string ClientID {
            get {
                return ResourceManager.GetString("ClientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户名称中含有 &lt;span style=&apos;Color:#F00&apos;&gt;{$Keyword}&lt;/span&gt; 的数据 的本地化字符串。
        /// </summary>
        internal static string ClientName {
            get {
                return ResourceManager.GetString("ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户ID等于 &lt;span style=&apos;Color:#F00&apos;&gt;{$Keyword}&lt;/span&gt; 的投诉记录 的本地化字符串。
        /// </summary>
        internal static string ComplainClientID {
            get {
                return ResourceManager.GetString("ComplainClientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户名称中含有 &lt;span style=&apos;Color:#F00&apos;&gt;{$Keyword}&lt;/span&gt; 的投诉记录 的本地化字符串。
        /// </summary>
        internal static string ComplainClientName {
            get {
                return ResourceManager.GetString("ComplainClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 投诉日期为 &lt;span style=&apos;Color:#F00&apos;&gt;{$Keyword}&lt;/span&gt; 的投诉记录 的本地化字符串。
        /// </summary>
        internal static string ComplainDate {
            get {
                return ResourceManager.GetString("ComplainDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系地址中含有 &lt;span style=&apos;Color:#F00&apos;&gt;{$Keyword}&lt;/span&gt; 的订单 的本地化字符串。
        /// </summary>
        internal static string ConsignmenAddress {
            get {
                return ResourceManager.GetString("ConsignmenAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  &lt;span style=&apos;Color:#F00&apos;&gt;{$Keyword}&lt;/span&gt; 代理的订单 的本地化字符串。
        /// </summary>
        internal static string ConsignmenAgentName {
            get {
                return ResourceManager.GetString("ConsignmenAgentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户名称中含有 &lt;span style=&apos;Color:#F00&apos;&gt;{$Keyword}&lt;/span&gt; 的订单 的本地化字符串。
        /// </summary>
        internal static string ConsignmenClientName {
            get {
                return ResourceManager.GetString("ConsignmenClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收货人姓名中含有 &lt;span style=&apos;Color:#F00&apos;&gt;{$Keyword}&lt;/span&gt; 的订单 的本地化字符串。
        /// </summary>
        internal static string ConsignmenContacterName {
            get {
                return ResourceManager.GetString("ConsignmenContacterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  &lt;span style=&apos;Color:#F00&apos;&gt;{$Keyword}&lt;/span&gt; 下单的订单 的本地化字符串。
        /// </summary>
        internal static string ConsignmenDateAndTime {
            get {
                return ResourceManager.GetString("ConsignmenDateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单编号中含有 &lt;span style=&apos;Color:#F00&apos;&gt;{$Keyword}&lt;/span&gt; 的订单 的本地化字符串。
        /// </summary>
        internal static string ConsignmenOrderNum {
            get {
                return ResourceManager.GetString("ConsignmenOrderNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系电话中含有 &lt;span style=&apos;Color:#F00&apos;&gt;{$Keyword}&lt;/span&gt; 的订单 的本地化字符串。
        /// </summary>
        internal static string ConsignmenPhone {
            get {
                return ResourceManager.GetString("ConsignmenPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 购买商品的名称中含有 &lt;span style=&apos;Color:#F00&apos;&gt;{$Keyword}&lt;/span&gt; 的订单 的本地化字符串。
        /// </summary>
        internal static string ConsignmenProductName {
            get {
                return ResourceManager.GetString("ConsignmenProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户的QQ中含有 &lt;span style=&apos;Color:#F00&apos;&gt;{$Keyword}&lt;/span&gt; 的订单 的本地化字符串。
        /// </summary>
        internal static string ConsignmenQQ {
            get {
                return ResourceManager.GetString("ConsignmenQQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注/留言中中含有 &lt;span style=&apos;Color:#F00&apos;&gt;{$Keyword}&lt;/span&gt; 的订单 的本地化字符串。
        /// </summary>
        internal static string ConsignmenRemark {
            get {
                return ResourceManager.GetString("ConsignmenRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名中含有 &lt;span style=&apos;Color:#F00&apos;&gt;{$Keyword}&lt;/span&gt; 的订单 的本地化字符串。
        /// </summary>
        internal static string ConsignmenUserName {
            get {
                return ResourceManager.GetString("ConsignmenUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系人ID为 &lt;span style=&apos;Color:#F00&apos;&gt;{$Keyword}&lt;/span&gt; 的数据 的本地化字符串。
        /// </summary>
        internal static string ContacterID {
            get {
                return ResourceManager.GetString("ContacterID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系人名称为 &lt;span style=&apos;Color:#F00&apos;&gt;{$Keyword}&lt;/span&gt; 的数据 的本地化字符串。
        /// </summary>
        internal static string ContacterName {
            get {
                return ResourceManager.GetString("ContacterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 优惠券号码中含有 &lt;span style=&apos;Color:#F00&apos;&gt;{$Keyword}&lt;/span&gt; 的数据 的本地化字符串。
        /// </summary>
        internal static string CouponNum {
            get {
                return ResourceManager.GetString("CouponNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 优惠券名称中含有 &lt;span style=&apos;Color:#F00&apos;&gt;{$Keyword}&lt;/span&gt; 的数据 的本地化字符串。
        /// </summary>
        internal static string CouponTitle {
            get {
                return ResourceManager.GetString("CouponTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名称中含有 &lt;span style=&apos;Color:#F00&apos;&gt;{$Keyword}&lt;/span&gt; 的数据 的本地化字符串。
        /// </summary>
        internal static string CouponUserName {
            get {
                return ResourceManager.GetString("CouponUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户名称中含有关键字 &lt;span style=&apos;color:#ff0000&apos;&gt;{$Keyword}&lt;/span&gt; 的记录 的本地化字符串。
        /// </summary>
        internal static string DeliverClientName {
            get {
                return ResourceManager.GetString("DeliverClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收货人姓名中含有关键字 &lt;span style=&apos;color:#ff0000&apos;&gt;{$Keyword}&lt;/span&gt; 的记录 的本地化字符串。
        /// </summary>
        internal static string DeliverConsignee {
            get {
                return ResourceManager.GetString("DeliverConsignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发退货日期为 &lt;span style=&apos;color:#ff0000&apos;&gt;{$Keyword}&lt;/span&gt; 的记录 的本地化字符串。
        /// </summary>
        internal static string DeliverDate {
            get {
                return ResourceManager.GetString("DeliverDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 经手人中含有关键字 &lt;span style=&apos;color:#ff0000&apos;&gt;{$Keyword}&lt;/span&gt; 的记录 的本地化字符串。
        /// </summary>
        internal static string DeliverDealer {
            get {
                return ResourceManager.GetString("DeliverDealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快递公司中含有关键字 &lt;span style=&apos;color:#ff0000&apos;&gt;{$Keyword}&lt;/span&gt; 的记录 的本地化字符串。
        /// </summary>
        internal static string DeliverExpressageCompany {
            get {
                return ResourceManager.GetString("DeliverExpressageCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快递单号中含有关键字 &lt;span style=&apos;color:#ff0000&apos;&gt;{$Keyword}&lt;/span&gt; 的记录 的本地化字符串。
        /// </summary>
        internal static string DeliverExpressageNum {
            get {
                return ResourceManager.GetString("DeliverExpressageNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名中含有关键字 &lt;span style=&apos;color:#ff0000&apos;&gt;{$Keyword}&lt;/span&gt; 的记录 的本地化字符串。
        /// </summary>
        internal static string DeliverUserName {
            get {
                return ResourceManager.GetString("DeliverUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最近 &lt;span style=&apos;color:#ff0000&apos;&gt;{$Keyword}&lt;/span&gt; 天的下载报错地址 的本地化字符串。
        /// </summary>
        internal static string ErrorDate {
            get {
                return ResourceManager.GetString("ErrorDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关键字中含有 &lt;span style=&apos;color:#ff0000&apos;&gt;{$Keyword}&lt;/span&gt; 的下载报错地址 的本地化字符串。
        /// </summary>
        internal static string InfoID {
            get {
                return ResourceManager.GetString("InfoID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户名称中含有 &lt;span style=&apos;color:#ff0000&apos;&gt;{$Keyword}&lt;/span&gt; 的记录 的本地化字符串。
        /// </summary>
        internal static string InvoiceClientName {
            get {
                return ResourceManager.GetString("InvoiceClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发票日期为 &lt;span style=&apos;color:#ff0000&apos;&gt;{$Keyword}&lt;/span&gt; 的记录 的本地化字符串。
        /// </summary>
        internal static string InvoiceDate {
            get {
                return ResourceManager.GetString("InvoiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开票人含有 &lt;span style=&apos;color:#ff0000&apos;&gt;{$Keyword}&lt;/span&gt; 的记录 的本地化字符串。
        /// </summary>
        internal static string InvoiceDealer {
            get {
                return ResourceManager.GetString("InvoiceDealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 链接地址中含有 &lt;span style=&apos;color:#ff0000&apos;&gt;{$Keyword}&lt;/span&gt; 的站内链接 的本地化字符串。
        /// </summary>
        internal static string LinkAddress {
            get {
                return ResourceManager.GetString("LinkAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 链接目标中含有 &lt;span style=&apos;color:#ff0000&apos;&gt;{$Keyword}&lt;/span&gt; 的站内链接 的本地化字符串。
        /// </summary>
        internal static string LinkTarget {
            get {
                return ResourceManager.GetString("LinkTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常规关键字含有 &lt;span style=&apos;color:#ff0000&apos;&gt;{$Keyword}&lt;/span&gt; 的关键字 的本地化字符串。
        /// </summary>
        internal static string NormalKeyword {
            get {
                return ResourceManager.GetString("NormalKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系人地址中含有 &lt;span style=&apos;color:#ff0000&apos;&gt;{$Keyword}&lt;/span&gt; 的订单 的本地化字符串。
        /// </summary>
        internal static string OrderAddress {
            get {
                return ResourceManager.GetString("OrderAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;span style=&apos;color:#ff0000&apos;&gt;{$Keyword}&lt;/span&gt; 代理的订单 的本地化字符串。
        /// </summary>
        internal static string OrderAgentName {
            get {
                return ResourceManager.GetString("OrderAgentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户名称中含有 &lt;span style=&apos;color:#ff0000&apos;&gt;{$Keyword}&lt;/span&gt; 的订单 的本地化字符串。
        /// </summary>
        internal static string OrderClientName {
            get {
                return ResourceManager.GetString("OrderClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收货人姓名中含有 &lt;span style=&apos;color:#ff0000&apos;&gt;{$Keyword}&lt;/span&gt; 的订单 的本地化字符串。
        /// </summary>
        internal static string OrderContacterName {
            get {
                return ResourceManager.GetString("OrderContacterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;span style=&apos;color:#ff0000&apos;&gt;{$Keyword}&lt;/span&gt; 下单的订单 的本地化字符串。
        /// </summary>
        internal static string OrderDateAndTime {
            get {
                return ResourceManager.GetString("OrderDateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收货人Email中含有 &lt;span style=&apos;color:#ff0000&apos;&gt;{$Keyword}&lt;/span&gt; 的订单 的本地化字符串。
        /// </summary>
        internal static string OrderEmail {
            get {
                return ResourceManager.GetString("OrderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跟单员中含有 &lt;span style=&apos;color:#ff0000&apos;&gt;{$Keyword}&lt;/span&gt; 的订单 的本地化字符串。
        /// </summary>
        internal static string OrderFunctionary {
            get {
                return ResourceManager.GetString("OrderFunctionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发票信息中含有 &lt;span style=&apos;color:#ff0000&apos;&gt;{$Keyword}&lt;/span&gt; 的订单 的本地化字符串。
        /// </summary>
        internal static string OrderInvoiceContent {
            get {
                return ResourceManager.GetString("OrderInvoiceContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内部记录中含有 &lt;span style=&apos;color:#ff0000&apos;&gt;{$Keyword}&lt;/span&gt; 的订单 的本地化字符串。
        /// </summary>
        internal static string OrderMemo {
            get {
                return ResourceManager.GetString("OrderMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收货人手机中含有 &lt;span style=&apos;color:#ff0000&apos;&gt;{$Keyword}&lt;/span&gt; 的订单 的本地化字符串。
        /// </summary>
        internal static string OrderMobile {
            get {
                return ResourceManager.GetString("OrderMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单编号中含有 &lt;span style=&apos;color:#ff0000&apos;&gt;{$Keyword}&lt;/span&gt; 的订单 的本地化字符串。
        /// </summary>
        internal static string OrderNum {
            get {
                return ResourceManager.GetString("OrderNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系电话中含有 &lt;span style=&apos;color:#ff0000&apos;&gt;{$Keyword}&lt;/span&gt; 的订单 的本地化字符串。
        /// </summary>
        internal static string OrderPhone {
            get {
                return ResourceManager.GetString("OrderPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 购买商品的名称中含有 &lt;span style=&apos;color:#ff0000&apos;&gt;{$Keyword}&lt;/span&gt; 的订单 的本地化字符串。
        /// </summary>
        internal static string OrderProductName {
            get {
                return ResourceManager.GetString("OrderProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户的QQ为 &lt;span style=&apos;color:#ff0000&apos;&gt;{$Keyword}&lt;/span&gt; 的订单 的本地化字符串。
        /// </summary>
        internal static string OrderQQ {
            get {
                return ResourceManager.GetString("OrderQQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注/留言中含有 &lt;span style=&apos;color:#ff0000&apos;&gt;{$Keyword}&lt;/span&gt; 的订单 的本地化字符串。
        /// </summary>
        internal static string OrderRemark {
            get {
                return ResourceManager.GetString("OrderRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名中含有 &lt;span style=&apos;color:#ff0000&apos;&gt;{$Keyword}&lt;/span&gt; 的订单 的本地化字符串。
        /// </summary>
        internal static string OrderUserName {
            get {
                return ResourceManager.GetString("OrderUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {@Field} &lt;span style=&apos;Color:#F00&apos;&gt;{$Keyword}&lt;/span&gt; 的在线支付记录 的本地化字符串。
        /// </summary>
        internal static string PaymentLog {
            get {
                return ResourceManager.GetString("PaymentLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {@SearchType}中含有 &lt;span style=&apos;color:#ff0000&apos;&gt;{$Keyword}&lt;/span&gt; 的厂商 的本地化字符串。
        /// </summary>
        internal static string ProducerManage {
            get {
                return ResourceManager.GetString("ProducerManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所属县区中含有关键字 &lt;span style=&apos;color:#ff0000&apos;&gt;{$Keyword}&lt;/span&gt; 的记录 的本地化字符串。
        /// </summary>
        internal static string RegionArea {
            get {
                return ResourceManager.GetString("RegionArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区号中含有关键字 &lt;span style=&apos;color:#ff0000&apos;&gt;{$Keyword}&lt;/span&gt; 的记录 的本地化字符串。
        /// </summary>
        internal static string RegionAreaCode {
            get {
                return ResourceManager.GetString("RegionAreaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所属城市中含有关键字 &lt;span style=&apos;color:#ff0000&apos;&gt;{$Keyword}&lt;/span&gt; 的记录 的本地化字符串。
        /// </summary>
        internal static string RegionCity {
            get {
                return ResourceManager.GetString("RegionCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮政编码中含有关键字 &lt;span style=&apos;color:#ff0000&apos;&gt;{$Keyword}&lt;/span&gt; 的记录 的本地化字符串。
        /// </summary>
        internal static string RegionPostCode {
            get {
                return ResourceManager.GetString("RegionPostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所属省份中含有关键字 &lt;span style=&apos;color:#ff0000&apos;&gt;{$Keyword}&lt;/span&gt; 的记录 的本地化字符串。
        /// </summary>
        internal static string RegionProvince {
            get {
                return ResourceManager.GetString("RegionProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 替换内容中含有 &lt;span style=&apos;color:#ff0000&apos;&gt;{$Keyword}&lt;/span&gt; 的关键字 的本地化字符串。
        /// </summary>
        internal static string ReplaceContent {
            get {
                return ResourceManager.GetString("ReplaceContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 替换目标中含有 &lt;span style=&apos;color:#ff0000&apos;&gt;{$Keyword}&lt;/span&gt; 的关键字 的本地化字符串。
        /// </summary>
        internal static string ReplaceTarget {
            get {
                return ResourceManager.GetString("ReplaceTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {@Field} &lt;span style=&apos;color:#ff0000&apos;&gt;{$Keyword}&lt;/span&gt; 的商品销售记录 的本地化字符串。
        /// </summary>
        internal static string SaleList {
            get {
                return ResourceManager.GetString("SaleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索关键字 &lt;span style=&apos;color:#ff0000&apos;&gt;{$Keyword}&lt;/span&gt; 的关键字 的本地化字符串。
        /// </summary>
        internal static string SearchKeyword {
            get {
                return ResourceManager.GetString("SearchKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {@Field} &lt;span style=&apos;Color:#F00&apos;&gt;{$Keyword}&lt;/span&gt; 的数据 的本地化字符串。
        /// </summary>
        internal static string ServiceSearch {
            get {
                return ResourceManager.GetString("ServiceSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单据编号是 &lt;span style=&apos;Color:#F00&apos;&gt;{$Keyword}&lt;/span&gt; 的有： 的本地化字符串。
        /// </summary>
        internal static string StockFormNum {
            get {
                return ResourceManager.GetString("StockFormNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 录入日期是 &lt;span style=&apos;Color:#F00&apos;&gt;{$Keyword}&lt;/span&gt; 的有： 的本地化字符串。
        /// </summary>
        internal static string StockInputDate {
            get {
                return ResourceManager.GetString("StockInputDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 录入者是 &lt;span style=&apos;Color:#F00&apos;&gt;{$Keyword}&lt;/span&gt; 的有： 的本地化字符串。
        /// </summary>
        internal static string StockInputPerson {
            get {
                return ResourceManager.GetString("StockInputPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {@SearchType} &lt;span style=&apos;Color:#F00&apos;&gt;{$Keyword}&lt;/span&gt; 的问卷 的本地化字符串。
        /// </summary>
        internal static string SurveySearch {
            get {
                return ResourceManager.GetString("SurveySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题中含有 &lt;span style=&apos;Color:#F00&apos;&gt;{$Keyword}&lt;/span&gt; 的日志 的本地化字符串。
        /// </summary>
        internal static string TitleText {
            get {
                return ResourceManager.GetString("TitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {@SearchType} &lt;span style=&apos;Color:#F00&apos;&gt;{$Keyword}&lt;/span&gt; 的数据 的本地化字符串。
        /// </summary>
        internal static string TrademarkManageSearch {
            get {
                return ResourceManager.GetString("TrademarkManageSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {@Field} &lt;span style=&apos;Color:#F00&apos;&gt;{$Keyword}&lt;/span&gt; 的订单记录  的本地化字符串。
        /// </summary>
        internal static string TransferLogSearch {
            get {
                return ResourceManager.GetString("TransferLogSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户IP中含有 &lt;span style=&apos;Color:#F00&apos;&gt;{$Keyword}&lt;/span&gt; 的日志 的本地化字符串。
        /// </summary>
        internal static string UserIPText {
            get {
                return ResourceManager.GetString("UserIPText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名称中含有 &lt;span style=&apos;Color:#F00&apos;&gt;{$Keyword}&lt;/span&gt; 的日志 的本地化字符串。
        /// </summary>
        internal static string UserNameText {
            get {
                return ResourceManager.GetString("UserNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消费时间为 &lt;span style=&apos;Color:#F00&apos;&gt;{$Keyword}&lt;/span&gt; 的有效期明细记录 的本地化字符串。
        /// </summary>
        internal static string ValidLogConsumeTime {
            get {
                return ResourceManager.GetString("ValidLogConsumeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名称中含有 &lt;span style=&apos;Color:#F00&apos;&gt;{$Keyword}&lt;/span&gt; 的有效期明细记录 的本地化字符串。
        /// </summary>
        internal static string ValidLogUserName {
            get {
                return ResourceManager.GetString("ValidLogUserName", resourceCulture);
            }
        }
    }
}
